#!/bin/bash

if [ $# -ne 1 ]; then
  echo "Usage $0 [-development | -production]"
  exit 1
fi

if [ "$1" == "-production" ]; then
  mode="production"
  export TF_CPP_MIN_LOG_LEVEL='3'
else
  mode="development"
  export TF_CPP_MIN_LOG_LEVEL='0'
fi

export NODE_ENV=$mode

echo "Starting server in $mode mode..."

envpath="./src/config/.env"

parallel --lb ::: "node --env-file=${envpath} --env-file=${envpath}.${mode} src/api.js" "node --env-file=${envpath} --env-file=${envpath}.${mode} src/media.js" & pid=$!

wait $pid

echo
echo "Server stopped"

