#!/bin/bash
cd $( dirname $0 )

if [ $# -ne 1 ]; then
  echo "Usage $0 [-development | -production]"
  exit 1
fi

if [ "$1" == "-production" ]; then
  mode="production"
  export TF_CPP_MIN_LOG_LEVEL='3'
else
  mode="development"
  export TF_CPP_MIN_LOG_LEVEL='0'
fi

export NODE_ENV=$mode
set -a
source ./src/config/.env
source ./src/config/.env.$mode
set +a
source ./.venv/bin/activate

# mysql -A -u $DB_USER -p -e "CREATE DATABASE IF NOT EXISTS $DB_DBNAME; USE $DB_DBNAME; source ./src/config/init_database.sql;"

npx tsc

echo "Starting server in $mode mode..."

parallel --lb ::: "python3 ./src/ml.py" "node built/api.js" "node built/media.js" "node built/website.js" & pid=$!

wait $pid

echo
echo "Server stopped"

