#!/bin/bash

if [ $# -ne 1 ]; then
  echo "Usage $0 [-development | -production]"
  exit 1
fi

if [ "$1" == "-production" ]; then
  mode="production"
  export TF_CPP_MIN_LOG_LEVEL='3'
else
  mode="development"
  export TF_CPP_MIN_LOG_LEVEL='0'
fi

export NODE_ENV=$mode

echo "Starting server in $mode mode..."

envpath=".env.${mode}"

parallel --lb ::: "node --env-file=.env --env-file=${envpath} api.js" "node --env-file=.env --env-file=${envpath} media.js" & pid=$!

wait $pid

echo
echo "Server stopped"

