#!/bin/bash

if [ $# -ne 1 ]; then
  echo "Usage $0 [-development | -production]"
  exit 1
fi

if [ "$1" == "-production" ]; then
  mode="production"
else
  mode="development"
fi

export NODE_ENV=$mode

echo "Starting server in $mode mode..."

envpath=".env.${mode}"

parallel --lb ::: 'sudo node --env-file .env.development api.js' 'sudo node --env-file .env.development media.js' & pid=$!

wait $pid

echo
echo "Server stopped"

